# Generated by Django 4.2.4 on 2023-09-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
